name: plato.cap
description: Summative and Formative review for CAP, written in AngularDart.
version: 0.3.0

author: Joseph B. Axenroth

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: ^0.14.0-alpha+1

dev_dependencies:
  angular_test: ^2.4.0
  build_runner: ^1.7.1
  build_test: ^0.10.9+1
  build_web_compilers: ^2.7.0
  sass_builder: ^2.1.3
  test: ^1.9.3
