name: plato.cap
description: Summative and Formative review for CAP, written in AngularDart.
version: 0.5.0+1

author: Joseph B. Axenroth

environment:
  sdk: '>=2.10.3 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.2

dev_dependencies:
  angular_test: ^3.0.0
  build_runner: ^1.10.4
  build_test: ^1.3.0
  build_web_compilers: ^2.12.2
  sass_builder: ^2.1.3
  test: ^1.15.4
